In [6]:
import sys
print('Python version')
print(sys.version)


Python version
3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


In [9]:
import datetime
now = datetime.datetime.now()
print(now)


2022-03-28 22:09:19.624606


In [12]:
r = int(input("enter the radius"))
areaOfCircle = 3.15*r*r
print("area of circle:",areaOfCircle )

enter the radius7
area of circle: 154.35


In [15]:
firstName = input("User First Name")
lastName = input("User last Name")
fullName = firstName + lastName 
print("UserFull name",fullName)

print("Reverse name",lastName+" "+firstName)

User First NameArchana
User last NameRauniyar
UserFull name ArchanaRauniyar
Reverse name Rauniyar Archana


enter a num1
['1']


TypeError: 'tuple' object is not callable

In [28]:
x = [1,2,3,4,5]
reverse=[]
for i in range(x[-1],x[0],x[1]):
    reverse.append(x[i])
    print(reverse)

In [121]:
x=[5,6,7]
x.reverse()
print(x)

[7, 6, 5]


In [49]:
#print natural number sum
i= 1
sum =0
while(i<=10):
    print(i)
    sum = sum+i
    i = i+1
print("sum of n nutaural number is:",sum)
    
    
    

1
2
3
4
5
6
7
8
9
10
sum of n nutaural number is: 55


In [39]:
#print natural number
i= 1
while(i<=10):
    print(i)
    i = i+1
    

1
2
3
4
5
6
7
8
9
10


In [37]:
#print natural number
i=0
for i in range(10):
    i=i+1
    print(i)

1
2
3
4
5
6
7
8
9
10


In [43]:
#print number from 1 to n
n = int(input("enter a number"))
i=1
while(i<=n):
    print(i)
    i=i+1 

enter a number12
1
2
3
4
5
6
7
8
9
10
11
12


In [45]:
#print natural number in reverse order
i= 10
while(i>=1):
    print(i)
    i = i-1

10
9
8
7
6
5
4
3
2
1


In [50]:
#print natural number square sum
i= 1
sum =0
while(i<=10):
    print(i)
    sum = sum+(i*i)
    i = i+1
print("sum of n nutaural number is:",sum)

1
2
3
4
5
6
7
8
9
10
sum of n nutaural number is: 385


In [56]:
#print even natural number 
n= int(input("enter a number"))
i= 2
while(i<=n):
    print(i)
    i = i+2


enter a number50
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [58]:
#print  sum of even  number 
n= int(input("enter a number"))
i= 2
sum =0
while(i<=n):
    sum=sum+i
    i = i+2
print("sum of even number",sum)    

enter a number6
sum of even number 12


In [63]:
#print  sum of n even  number 
n= int(input("enter a number"))
i= 2
sum =0
count=0
while(count<n):
        if(i%2==0):
            sum=sum+i
            count =count+1
        i = i+1
print("sum of n even number",sum)

enter a number3
sum of n even number 12


In [72]:
#sum of digit of a given number 
x="234"

# val =x.split(',')
sum=0
# print(val)
for i in x:
    sum=sum+int(i)
print(sum)

9


In [75]:

x="234"
sum=0
# print(val)
for i in x:
    val = int(i)**2
    sum=sum+val
print(sum)

29


In [81]:
#check whether given number is amrstrong or not
x = (input("enter a number"))
sum=0
for i in x:
    cube = int(i)**3
    sum=sum+cube
if sum == int(x):
    print("it is armstrong %s is  equal to %s",sum,int(x))
else:
    print("it is not armstrong coz %s is not equal to %s",sum,int(x))
print(sum)      

enter a number153
it is armstrong %s is  equal to %s 153 153
153


In [84]:
#product of digit og given number
x = (input("enter a number"))
product=1
for i in x:
    intVal=int(i)
    product=product*intVal
print(product)    
   

enter a number123
6


In [90]:
#product of digit og given number
x = (input("enter a number"))
sum=0
pro=1
for i in x:
    intVal=int(i)
    if intVal%2==0:
        sum =sum+intVal
        print("sum of even",sum)
    else:
        pro=pro*intVal
        print("product of odd",pro)
        
    

enter a number12345
product of odd 1
sum of even 2
product of odd 3
sum of even 6
product of odd 15


In [97]:
#find the reverse of given number
x =str(input("enter a number"))
rev_val = x[::-1]
print(rev_val)
# for i in range(len(x)-1,0,1):
#     print(i)


enter a number123
321


In [99]:
#find the reverse of given number
x =int(input("enter a number"))
rev=0
while(x>0):
    rev= (rev*10)+x%10
    x = x//10
print("Reverse",rev)

enter a number98765
Reverse 56789


In [101]:
#check whether number is palindrome or not
x =str(input("enter a number"))
rev_val = x[::-1]
print(rev_val)
if x==rev_val:
    print("it is palindrome")
else:
     print("it is not palindrome")
    

enter a number123
321
it is not palindrome


In [102]:
#check where given number is prime or not
n=int(input("Enter a number :"))
i=1
count =0
while(i<=n):
    if n%i==0:
        count=count+1
    i=i+1
if count==2:
    print("it is prime number")
else:
    print("it is not prime number")
        

Enter a number :7
it is prime number


In [103]:
#find the factorila of given number
n=int(input("Enter a number :"))
fac=1
while(n>0):
    fac=fac*n
    n=n-1
print(fac)    
    


Enter a number :5
120


In [111]:
#write a fiboanicces series of a given number
n=int(input("Enter a number :"))
x=0
y=1
z=0
while(z<=n):
    print(z)
    x=y
    y=z
    z=x+y
    
    


Enter a number :10
0
1
1
2
3
5
8


In [113]:
#print a start
i =1
while(i<=5):
    j=1
    while(j<=i):
        print('*',end=(' '))
        j=j+1
    print()    
    i=i+1    

* 
* * 
* * * 
* * * * 
* * * * * 


In [115]:
#print a start
i =1
while(i<=5):
    j=1
    while(j<=i):
        print(j,end=(' '))
        j=j+1
    print()    
    i=i+1 

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [116]:
#print a start
i =1
while(i<=5):
    j=1
    while(j<=i):
        print(i,end=(' '))
        j=j+1
    print()    
    i=i+1 

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [118]:
#print a start in reverse order
i =5
while(i>=1):
    j=5
    while(j>=i):
        print(i,end=(' '))
        j=j-1
    print()    
    i=i-1 


5 
4 4 
3 3 3 
2 2 2 2 
1 1 1 1 1 


In [120]:
#print a start in reverse order
i =1
while(i<=5):
    j=1
    while(j>=i):
        print(i,end=(' '))
        j=j-1
    print()    
    i=i-1 

1 
0 0 
-1 -1 -1 
-2 -2 -2 -2 
-3 -3 -3 -3 -3 
-4 -4 -4 -4 -4 -4 
-5 -5 -5 -5 -5 -5 -5 
-6 -6 -6 -6 -6 -6 -6 -6 
-7 -7 -7 -7 -7 -7 -7 -7 -7 
-8 -8 -8 -8 -8 -8 -8 -8 -8 -8 
-9 -9 -9 -9 -9 -9 -9 -9 -9 -9 -9 
-10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10 -10 
-11 -11 -11 -11 -11 -11 -11 -11 -11 -11 -11 -11 -11 
-12 -12 -12 -12 -12 -12 -12 -12 -12 -12 -12 -12 -12 -12 
-13 -13 -13 -13 -13 -13 -13 -13 -13 -13 -13 -13 -13 -13 -13 
-14 -14 -14 -14 -14 -14 -14 -14 -14 -14 -14 -14 -14 -14 -14 -14 
-15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 
-16 -16 -16 -16 -16 -16 -16 -16 -16 -16 -16 -16 -16 -16 -16 -16 -16 -16 
-17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 -17 
-18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 -18 
-19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 -19 
-20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20 
-21 -21 -21 -21 -21 -21 -21 -21 -21

-63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 -63 
-64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 -64 
-65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 -65 
-66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -66 -

-92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 -92 
-93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 -93 
-94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -94 -9

-113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 -113 
-114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114 -114

-129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 -129 
-130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130 -130

-145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 -145 
-146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146 -146

-157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 -157 
-158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158 -158

-177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 -177 
-178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178 -178

-188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 -188 
-189 -189 -189 -189 -189 -189 -189 -189 -189 -189

KeyboardInterrupt: 

In [131]:
#Write a program that adds n numbers and prints the sum
n=int(input("Enter a number:"))
sum=0
i=1
while(n>0):
    sum=sum+n
    n=n-1
print(sum)    

Enter a number:3
6


In [134]:
def sum(n):
    sum=0
    while(n>0):
        sum=sum+n
        n=n-1
    print("sum of n number:",sum)
sum(3)    

sum of n number: 6


In [137]:
#concatenate two tuples
tup1=(1,"a","Apple")
tup2=(2,"b","Ball")
tuples =tup1+tup2
print(tuples)

(1, 'a', 'Apple', 2, 'b', 'Ball')


In [139]:
#initialize 5x5 numpy array with only zeros
import numpy as np
init = np.zeros((5,5))
print(init)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [143]:
#creating series
import pandas as pd
data=[1,2,"abc"]
oneDim= pd.Series(data)
print(oneDim)
print(type(oneDim))

0      1
1      2
2    abc
dtype: object
<class 'pandas.core.series.Series'>


In [148]:
#create dataframes from list
import pandas as pd
df=pd.DataFrame()
list1 =["Apple","Ball","Cat","Dog"]
list2 =["Eat","Play","Meow","Bark"]   
df ["list1"]=list1
df ["list2"]=list2
print(df)

AttributeError: module 'numpy' has no attribute 'matrix'

In [150]:
#central tendency for numpy array
import numpy as np
n1=np.array([1,5,5,3,100,4,48])
print(np.mean(n1))
print(np.median(n1))
print(np.std(n1))

23.714285714285715
5.0
34.73044891205198


In [6]:
import string
x ="hello world I am archana rauniyar"
x=x.replace(" ","")
print(x)
y=string.capwords(x)
print(y)


helloworldIamarchanarauniyar
Helloworldiamarchanarauniyar


In [9]:
import re 
def convert_into_uppercase(a):
    return a.group(1) + a.group(2).upper()
s ="hello world I am archana rauniyar"
result = re.sub("(^|\s)(\S)", convert_into_uppercase, s)
result= result.replace(" ","")
print(result)


HelloWorldIAmArchanaRauniyar


In [ ]:



def sumOfProductOfDigits(n1):
 
    sum1 = 0;
    while (n1 > 0 ):
 
        sum1 += ((n1 % 10) * (n1-1 % 10));
        n1 = n1 // 10;
    
         
    return sum1;

 
print(sumOfProductOfDigits(n1));