In [1]:
#update the value of dictionary
vegetables={"Onion":60,"Tomato":25,"Potato":50}
vegetables["Onion"]=50
print(vegetables)

{'Onion': 50, 'Tomato': 25, 'Potato': 50}


In [3]:
#find common element in sets
s1={1,2,3,4,5}
s2={4,5,6,7,8}
s1.intersection(s2)



{4, 5}

In [ ]:
n=input("Enter a number:")
rev_val=n[::-1]
if n==rev_val:
    print("number is palindrome")
else:
    print("number is not palindrome")

In [8]:
#print a patter
n=int(input("Enter a number:"))
i=1
while(i<=n):
    j=1
    while(j<=i):
        print(i,end=" ")
        j=j+1
    print()     
    i=i+1

Enter a number:5
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [9]:
#print a patter for #
n=int(input("Enter a number:"))
i=1
while(i<=n):
    j=1
    while(j<=i):
        print("#",end=" ")
        j=j+1
    print()     
    i=i+1

Enter a number:5
# 
# # 
# # # 
# # # # 
# # # # # 


In [10]:
#print a patter for 
n=int(input("Enter a number:"))
i=1
while(i<=n):
    j=1
    while(j<=i):
        print(j,end=" ")
        j=j+1
    print()     
    i=i+1

Enter a number:5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
#print the pascal triangle petter


In [ ]:
#print ABC patter

In [4]:
#increment values of all keys in dictionary 
vegetables={"Onion":60,"Tomato":25,"Potato":50}
for k,v in vegetables.items():
    print("original price:",k,v)
    v=v+10
    print("increment price:",k,v)

original price: Onion 60
increment price: Onion 70
original price: Tomato 25
increment price: Tomato 35
original price: Potato 50
increment price: Potato 60


In [6]:
#print the random number using random library
import random as rd
num=rd.randint(1,10)
print(num)

5


In [10]:
#denote the use of args and kwargs in python
def argument(*args,**kwargs):
    print("args value",args)
    for k,v in kwargs.items():
        print("key value",k,v)
argument("Hello",Ram="sita",Krishna="Radha",Shiv="Parwati")        

args value ('Hello',)
key value Ram sita
key value Krishna Radha
key value Shiv Parwati


In [15]:
#examples for shallow copy in python
import copy
x1=[1,2,3,4,5]
x2=copy.copy(x1)
print(id(x1))
print(id(x2))
x2[1]=0
print(x2)
print(x1)

2567749001728
2567748717184
[1, 0, 3, 4, 5]
[1, 2, 3, 4, 5]


In [16]:
x1=[1,2,3,4,5]
x2=x1
x2[0]=0
print(x1)

[0, 2, 3, 4, 5]


In [19]:
a=[1,2,3,4,5,6,7,8,9]
x=a[-1:-4:-1]
print(x)

[9, 8, 7]


In [21]:
#printing ASCII value of given character
val="a"
print("ASCII value"+val+"is",ord(val))

ASCII valueais 97


In [26]:
#easiset way to suffle list
from random import shuffle 
value=["Hello","i","am","Archana","Rauniyar"]
shuffle(value)
print(value)


['i', 'Archana', 'Rauniyar', 'am', 'Hello']


In [27]:
#florr division in python
x=7//2
print(x)

3


In [28]:
#out of piece of code
"Hello World"[::-1]

'dlroW olleH'

In [29]:
#operation of list
list=[1,2,3,4]
list*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [31]:
#check when the given number is amrstrong or not to doooooo
val=int(input("Enter a number:"))
sum=0
while(val>0):
    digit=val%10
    sum +=digit**3
    val //=10
if val==sum:
    print("it is armstrong")
else:
     print("it is not armstrong")
    

Enter a number:153
it is not armstrong


In [5]:
#logic to print perferct number in python
val=int(input("Enter a number:"))
sum=0
i=1
while(i<val):
    if val%i==0:
        sum+=i
    i += 1 
if val==sum:
    print(val,"is perferct number")
else:
     print(val,"is not perferct number")

Enter a number:28
28
28
28 is perferct number


In [6]:
#logic to print strong nuber in python
sum1=0
num=int(input("Enter a number:"))
temp=num
while(num):
    i=1
    f=1
    r=num%10
    while(i<=r):
        f=f*i
        i=i+1
    sum1=sum1+f
    num=num//10
if(sum1==temp):
    print("The number is a strong number")
else:
    print("The number is not a strong number")
    


Enter a number:145
The number is a strong number


In [14]:
#find out largest number in list
list1 =[4,7,9,3,5]
list1.sort()
print(list1)
print("sceond largets number",list1[-2])

[3, 4, 5, 7, 9]
sceond largets number 7


In [15]:
#quickly swap the first and last element in list
list1=[4,7,9,3,5]
last_ele=list1[-1]
first_ele=list1[0]
list1[0]=last_ele
list1[-1]=first_ele
print(list1)

[5, 7, 9, 3, 4]


In [19]:
#count number of vowels present in string
word="helloi"
vowels=["a","e","i","o","u"]
sum=0
for i in word:
    if i in vowels:
         sum+=1
print(sum)    
    

3


In [ ]:
#break list into n chunks 


In [22]:
#denote the working of exception handling
try:
    x=int(input("Enter a number:"))
    y=int(input("Enter a number:"))
    z=x/y
    print("The output of division",z)
except Exception as e:
    print("some thing went wrong",e)
else:
    print("everthing is correct")
    

Enter a number:4
Enter a number:2
The output of division 2.0
everthing is correct


In [23]:
#how does finally block works in python
try:
    x=int(input("Enter a number:"))
    y=int(input("Enter a number:"))
    z=x/y
    print("The output of division",z)
except Exception as e:
    print("some thing went wrong",e)
finally:
    print("everthing is correct")

Enter a number:4
Enter a number:2
The output of division 2.0
everthing is correct


In [3]:
#create class human with name and age attributes
class human:
    def __init__(self,name,age):
        self.name=name
        self.age=age
        print(name,"age is",age)
person1=human("ram",16)
print(person1)
    

ram age is 16


In [6]:
class human:
    def get_name_age(self):
        self.name=input("Enter ur name ")
        self.age=input("enter ur age")
    def put_name_age(self):
        print("Your name is",self.name)
        print("Your age is",self.age)
person1=human()
person1.get_name_age()

Enter ur name Archana Rauniyar
enter ur age22


In [7]:
person1.put_name_age()

Your name is Archana Rauniyar
Your age is 22


In [10]:
class student:
    def __init__(self,name,age,branch):
        self.name=name
        self.age=age
        self.branch=branch
    def print_student(self):
        print("Student name is ",self.name)
        print("Student age is ",self.age)
        print("Student branch is ",self.branch)
person=student("Ram",16,"IT")
person.print_student()
    

Student name is  Ram
Student age is  16
Student branch is  IT


In [27]:
#inheritance concept in python

class school:
    def __init__(self,name,age,branch):
        self.name=name
        self.age=age
        self.branch=branch
    def print_student(self):
        print("Student name is ",self.name)
        print("Student age is ",self.age)
        print("Student branch is ",self.branch)
class teacher(school):
    def __init__(self,name,age,branch,subject,salary):
        super().__init__(name,age,branch)
        self.subject=subject
        self.salary=salary
       
    def teacher_info(self):
        print(self.name,"is teacher name.his age is:",self.age,"His salay is",self.salary,"he teach",self.subject,"subject")
person1=teacher("Ram",22,"Teacher","Science",200000)
person1.teacher_info()


        
    
    

Ram is teacher name.his age is: 22 His salay is 200000 he teach Science subject


In [36]:
#create 1-D or 2-D numpy array
import numpy as np
from random import shuffle 
list=[1,2,3,4,5]
a=np.array(list)
print("creating 1-D array:",a)
shuffle(a)
print("shuffle array values:",a)
a.sort()
print("sorting array values:",a)

creating 1-D array: [1 2 3 4 5]
shuffle array values: [3 5 1 2 4]
sorting array values: [1 2 3 4 5]


In [37]:
#creating 2-D list
import numpy as np
list=[[1,2,3,],
     [4,5,6]]
a=np.array(list)
print(a)


[[1 2 3]
 [4 5 6]]


In [40]:
#creating 2-D list
import numpy as np
a=np.array([[1,2,3],
     [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [43]:
#initialize 585 array comparisiong of all zeros
import numpy as np
a=np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
#sum of 2 array yby row
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
arr_sum=np.sum((a,b),axis=0)
print(arr_sum)

[2 4 6]


In [47]:
#sum of 2 array by column
import numpy as np
a=np.array([1,2,3])
b=np.array([1,2,3])
arr_sum=np.sum((a,b),axis=1)
print(arr_sum)

[6 6]


In [49]:
#getting n larget number
list=[3,9,8,7,5,5,8]
list.sort()
print(list[-1])

9


In [55]:
#removing repeated number from list
list=[3,9,8,7,5,5,8]
new_list=[]
for i in list:
    if i not in new_list:
        new_list.append(i)
print(new_list)    


[3, 9, 8, 7, 5]


In [57]:
#convert dataframe from list
import pandas as pd
list=[1,2,3,5,6,7]
data=pd.DataFrame(list)
print(data)

   0
0  1
1  2
2  3
3  5
4  6
5  7


In [66]:
#convert dataframe from dictionary
import pandas as pd
dic={"Baby":["Ram"],"Young":["Shyam"],"Teenage":["Sita"],"Adult":["Geeta"]}
val=pd.DataFrame(dic)
print(val)

  Baby  Young Teenage  Adult
0  Ram  Shyam    Sita  Geeta


In [ ]:
#open and read a file in python
file1=open('file.txt','r')
file1.read()


In [70]:
#create a lamda function to add 10 to a given number
val = lambda a: a+10
val(2)    

12

In [79]:
#create a lamda function to sum a list values
from functools import reduce
list1=[1,2,3,4,5,6]
sum_num=reduce(lambda x,y:x+y,list1)
print(sum_num)

21


In [83]:
#program to get the length of the string without using the len() function
val="ophthalmology"
sum=0
j=0
for i in val:
    sum+=1
print(sum)    
    

13


In [86]:
#replace all the odd number in this numpy array to -1
import numpy as np
arr=np.arange(0,10)
print(arr)
arr[arr%2==1]=-1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [94]:
#select the common elemnt in array
import numpy as np
l1=np.array([1,2,3,4,5])
l2=np.array([5,6,7,8,9])
np.intersect1d(l1,l2)


array([5])

In [96]:
#
import pandas as pd
ser=pd.Series(['mary','had','a','home'])
ser.map(lambda x:x.title())

0    Mary
1     Had
2       A
3    Home
dtype: object

In [97]:
#calculate the number of character in each word in a series
import pandas as pd
ser=pd.Series(['mary','had','a','home'])
ser.map(lambda x:len(x))

0    4
1    3
2    1
3    4
dtype: int64